### ISSUE TITLE
データを追加するときに外部キー制約のために処理が進まない

### ISSUE THREAD

**Issue by hiraikatsuyuki** [hiraikatsuyuki/prepare_kaken_dataset#1]
2020年度採択データを追加する際に、Part2-2 の研究分野マスタので、外部キー制約が外せていないので、処理が進まない。field_pathが問題。
IntegrityError: (pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails') [SQL: '\nDROP TABLE `fields`']

part3もinstitution マスターも外部キーを設定するところでもエラーが発生する

**Comment by hiraikatsuyuki** [comment]
df.to_sql()を実行する場面について、ひととおり外部キー制約を外す作業が必要かどうか洗い出す必要がありそう

**Comment by MeikoUesaka** [comment]
Kaken のマスターテーブルが4日前に更新されていたので（field_master とinstitution_master）part3を再トライ．セル番号21のところで，前はcategory_niicodeとsection_niicodeのキーは外せて，institution_niicodeでエラーになったのに，今日はsection_niicodeのところで下記エラー．
InternalError: (pymysql.err.InternalError) (1005, 'Can\'t create table `kaken`.`#sql-1530e_2e` (errno: 150 "Foreign key constraint is incorrectly formed")') [SQL: 'ALTER TABLE grantaward ADD CONSTRAINT section_niicode_1 FOREIGN KEY (section_niicode) REFERENCES sections(section_niicode);']

**Comment by hiraikatsuyuki** [comment]
外部キー制約を外したり付けたりする作業を、今は、それぞれ個々のdf.to_sql()の前後でやっているのですが、コードの見通しをよくするために、まとめてやった方がいい気もしてきました。データを更新したい場合は、けっきょく、テーブルを最初から全部作り直すことになるわけで、それを踏まえて、作業方針案を2つ考えました。

案1　データを更新する場合は、最初に外部キー制約を全部外すクエリを実行して、テーブルを更新したら、テーブルを作り終わってから、最後に一気に付ける。外部キー制約を全部洗いだすコマンドはあるようだけど、なんだかややこしそう
 
案2　外部キー制約は、一時的に無効にできるようなので(*1)、最初に無効にして、テーブルを全部更新したら、最後に外部キー制約を有効にする。(*1) https://mimirswell.ggnet.co.jp/blog-214
案2なら、外部キー制約の設定は、個々のdf.to_sql()のあとでもいいですが、最後にまとめて書いてもいいですね。

案2ですかねー

**Comment by MeikoUesaka** [comment]
案2，いいですね．

Part2のエラー出なくなりました．Part3を見てconstrain の名前を調べて，それと同じ名前をDROP FOREIGN KEY の後ろに入れたら出なくなりました．ちゃんとpython やmysqlを勉強してないので，暗号文を解いているようなやり方でのアプローチ，エラーが出ないからといって狙い通りにできてるかどうかは謎ですが，平井さんのヒントくらいにはなることを期待です．セルの番号を上から順番に降ったとき
[6]
        con.execute("ALTER TABLE grantaward_field DROP FOREIGN KEY fk_grantaward_field_field_niicode;")
        con.execute("ALTER TABLE grantaward_field DROP FOREIGN KEY fk_grantaward_field_field_path;")
[11]
        con.execute("ALTER TABLE grantaward_review_section DROP FOREIGN KEY fk_grantaward_review_section_review_section_niicode;")

としたら動きました．

**Comment by MeikoUesaka** [comment]
Part3 のsection_niicode の (errno: 150 "Foreign key constraint is incorrectly formed") は課題によってはsection_niicode がNoneとなっていることが原因のようです．テーブルsections にNoneの場合のために１行追加するのが良いのでしょうか？

**Comment by MeikoUesaka** [comment]
もともとのPart3 のエラー，institution_niicode が原因のものは，5月に入ってから更新されたinstitution のマスターファイルを使うとクリアできた模様です．具体的に新しく追加された研究機関がどこだったのかは追求してないです．コードかけるようになれば，そういうデバッグもさらっとできるのかなあと思いました

**Comment by MeikoUesaka** [comment]
Part3が複数回目のときは，セル[20]で例によって外部キーのエラーが出るので，がっつりと

# 外部キー制約を外す
try:
    with engine.connect() as con:
        con.execute("ALTER TABLE grantaward_review_section DROP FOREIGN KEY fk_grantaward_review_section_grantaward;")
        con.execute("ALTER TABLE grantaward_field DROP FOREIGN KEY fk_grantaward_field_grantaward;")
        con.execute("ALTER TABLE grantaward_annual DROP FOREIGN KEY fk_grantaward_annual_grantaward;")
        con.execute("ALTER TABLE grantaward_member DROP FOREIGN KEY fk_grantaward_member_grantaward;")
        con.execute("ALTER TABLE grantaward_paragraph DROP FOREIGN KEY fk_grantaward_paragraph_grantaward;")
        con.execute("ALTER TABLE grantaward_keyword DROP FOREIGN KEY fk_grantaward_keyword_grantaward;")
        con.execute("ALTER TABLE grantaward_product DROP FOREIGN KEY fk_grantaward_product_grantaward;")
except:
    pass

と入れました．これでエラーは出なくなりましたが，この動けばいい精神が平井さんが書いてくれた綺麗なコードを汚くしてしまっているようで申し訳なく思ってます．

**Comment by hiraikatsuyuki** [comment]
ありがとうございます。案2で考えていきましょう。

> Part3 のsection_niicode の (errno: 150 "Foreign key constraint is incorrectly formed") は課題によってはsection_niicode がNoneとなっていることが原因のようです．テーブルsections にNoneの場合のために１行追加するのが良いのでしょうか？

自分の勉強不足ですが、NULLを含むカラムの外部キー制約って、どういう扱いになるんでしょうね。あとで調べます

> もともとのPart3 のエラー，institution_niicode が原因のものは，5月に入ってから更新されたinstitution のマスターファイルを使うとクリアできた模様です．具体的に新しく追加された研究機関がどこだったのかは追求してないです．コードかけるようになれば，そういうデバッグもさらっとできるのかなあと思いました

外部キー制約の仕組みは、まさしくそのようなデータ間の不整合を浮かび上がらせて、テーブルをデータ分析に供する前に、ちゃんと不整合を解消させるためのチェック機構といえるのかなと思いました。どの機関が追加されたかはNIIに任せて、我々はいつもただただNIIをキャッチアップできるコードが、これから書ければいいなと思います

**Comment by MeikoUesaka** [comment]
> 自分の勉強不足ですが、NULLを含むカラムの外部キー制約って、どういう扱いになるんでしょうね。あとで調べます
自分はすぐNULLの場合はゼロとか上限値的な数値とかに置き換えることを考えてしまい，その場しのぎでやり過ごそうとしてしまうところが恥ずかしくなりました．「なるほど」という処理の仕方，面白そうです．

> 外部キー制約の仕組みは、まさしくそのようなデータ間の不整合を浮かび上がらせて
2年前平井さんが書かれたマスターファイルをパースするコードを一つ動かしてみて，「んでこれが？」という感じだったのですが，今はわかります．

**Comment by MeikoUesaka** [comment]
pull request してみました．
MeikoUesaka wants to merge 1 commit into hiraikatsuyuki:master from MeikoUesaka:foreign-key
となっていますが，mergeするのは平井さんという理解でよいでしょうか？

Part3のsection_niicodeのところで出ていたエラーは出なくなりました．これも，外部制約キーが関係していたということになるのかと思ったりしています．再現性の確認がイマイチですみません．

**Comment by hiraikatsuyuki** [comment]
ということで、おかげさまでプルリクエストをマージできましたので、このissueは終わりということにしたいと思います。ありがとうございました。
